/* AUTO-GENERATED BY Z-SCANNER - DO NOT EDIT */
#ifndef Z_REGISTRY_H
#define Z_REGISTRY_H

/* Vectors */
#define Z_AUTOGEN_VECS(X) \
    /* No vectors found */

/* Lists */
#define Z_AUTOGEN_LISTS(X) \
    /* No lists found */

/* Maps */
#define Z_AUTOGEN_MAPS(X) \
    X(int, float, IntFloat) \
    X(char*, int, StrInt) \

#endif // Z_REGISTRY_H
